version: "3"

services:

  users-service:
    build: ./users-service
    ports:
      - "5001:5000"

  turns-service:
    build: ./turns-service
    ports:
      - "5002:5000"

  notifications-service:
    build: ./notifications-service
    ports:
    - "5003:5000"    